# Generated by Django 4.2.4 on 2023-09-02 17:39

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=30)),
                ('table_type', models.CharField(choices=[('two_to_four_table', 'Two to Four Person Table'), ('bar_height_table', 'Bar Height Tables'), ('family_table', 'Family Dining Tables'), ('booth_table', 'Booths'), ('outdoor_table', 'Outdoor Tables')], max_length=30)),
                ('seating_capacity', models.PositiveIntegerField(default=2)),
                ('table_status', models.BooleanField(default=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='table_name', unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='VisitedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_user_name', models.CharField(max_length=30)),
                ('visited_user_email', models.EmailField(max_length=50)),
                ('visited_phone_number', models.CharField(max_length=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.CharField(max_length=50)),
                ('reservation_email', models.EmailField(max_length=50)),
                ('reservation_phone', models.CharField(max_length=20)),
                ('reservation_date', models.DateField(verbose_name='Reservation Date')),
                ('reservation_time', models.TimeField(verbose_name='Reservation Time')),
                ('reservation_message', models.CharField(max_length=255)),
                ('persons', models.PositiveIntegerField(verbose_name='Persons')),
                ('reservation_status', models.CharField(choices=[('in_review', 'In Review'), ('reserved', 'Reserved'), ('cancelled', 'Cancelled')], default='in_review', max_length=10)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.maketable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
