# Generated by Django 4.2.4 on 2023-09-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedusers',
            name='user',
        ),
    ]
