# Generated by Django 4.2.4 on 2023-09-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_remove_visitedusers_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitedusers',
            options={'verbose_name_plural': 'Visited Users'},
        ),
    ]
