# Generated by Django 4.2.4 on 2023-09-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_visitedusers_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('reserved', 'Reserved'), ('is_cancelled', 'Cancelled')], default='in_review', max_length=15),
        ),
    ]
